## Snowshoe hares at Bonanza Creek Experimental Forest

## 1. Archive Exploration

a. Take some time to look through the dataset’s description in EDI and click around. Then click on View Full Metadata, go to the “Detailed Metadata” section and click on “Data Entities” to look at the descriptions for the dataset’s columns.

b. Use the dataset’s description and the metadata to answer the following questions:

Who assembled this data, and why?
> The Bonanza Creek LTER assembled the data to study the Snowshoe hares, Lepus americanus, which are a 'keystone' prey species in northern boreal forests. The study's aim was to examine how the Snowshoe hares population fluctuated over the course of 8-11 years.

What does a single row in the data represent?
> A single row in the data represents an observation from one hare.

When and where were the observations collected?
> The observations were collected from 1990-06-01 to 2012-09-14 in the  northern boreal forests of Alaska.

Does the dataset contain sensitive data?
> The data does not contain sensitive data.

What study protocols were used to collect the data?
> The protocols are not explicitly listed but they do provide detailed information of the different sampling sites that were used in this study. 

What are the units for the hares’ weight?
> The unit for the hares' weight are in grams.

Does the metadata say how missing data is encoded?
> It does not but it does include a disclaimer that there were substantial efforts are made to ensure the accuracy of data and documentation contained in this Data Set. 

Is there a publication associated with this dataset?
> No there is not.

c. In your notebook: use a markdown cell to briefly answer these questions. Include as well a citation, date of access, and a link to the archive.

Citation for dataset:
> Kielland, K., F.S. Chapin, R.W. Ruess, and Bonanza Creek LTER. 2017. Snowshoe hare physical data in Bonanza Creek Experimental Forest: 1999-Present ver 22. Environmental Data Initiative. https://doi.org/10.6073/pasta/03dce4856d79b91557d8e6ce2cbcdc14 (Accessed 2026-10-15).

Date of Access:
> 15 October 2026

Link to archive: 
> https://portal.edirepository.org/nis/mapbrowse?packageid=knb-lter-bnz.55.22

d. Before you look at the data itself, think about what you learned about how this data was collected. In a markdown cell, write down two or three questions about possible issues you might find in the data.
> An issue with the dataset could be how the observations were recorded and if they followed the same format throughout the dataset. Another issue would be missing or NA values in columns that would contribute to the analysis.

## 2. Adding an image

![Snowshoe Hare](https://upload.wikimedia.org/wikipedia/commons/8/8a/SNOWSHOE_HARE_%28Lepus_americanus%29_%285-28-2015%29_quoddy_head%2C_washington_co%2C_maine_-01_%2818988734889%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=index&utm_content=original)

## 3. Data loading and preliminary exploration

Back in your notebook, import the 55_Hare_Data_2012.txt file available here. Store it in a variable named hares.

In [3]:
import pandas as pd
import numpy as np


hares = pd.read_csv('data/55_Hare_Data_2012.txt')
hares.head()

,date,time,grid,trap,l_ear,r_ear,sex,age,weight,hindft,notes,b_key,session_id,study
0,11/26/1998,NaN,bonrip,1A,414D096A08,NaN,NaN,NaN,1370.0,160.0,NaN,917.0,51,Population
1,11/26/1998,NaN,bonrip,2C,414D320671,NaN,M,NaN,1430.0,NaN,NaN,936.0,51,Population
2,11/26/1998,NaN,bonrip,2D,414D103E3A,NaN,M,NaN,1430.0,NaN,NaN,921.0,51,Population
3,11/26/1998,NaN,bonrip,2E,414D262D43,NaN,NaN,NaN,1490.0,135.0,NaN,931.0,51,Population
4,11/26/1998,NaN,bonrip,3B,414D2B4B58,NaN,NaN,NaN,1710.0,150.0,NaN,933.0,51,Population

Using pandas methods, obtain preliminary information and explore this data frame. Consider answering some of these questions:

- What are the dimensions of the data frame?

In [4]:
hares.shape

(3380, 14)

- What are the data types of the columnso and do the data types match what you would expect from each column?
    - Yes, based off the output of .dtypes, the columns are treated as the correct data type

In [5]:
hares.dtypes

date           object
time           object
grid           object
trap           object
l_ear          object
r_ear          object
sex            object
age            object
weight        float64
hindft        float64
notes          object
b_key         float64
session_id      int64
study          object
dtype: object

- Are there any columns that have a significant number of NA values?
    - Yes, the time column has a lot of null values in comparison to the other columns

In [7]:
hares.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3380 entries, 0 to 3379
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        3380 non-null   object
 1   time        264 non-null    object
 2   grid        3380 non-null   object
 3   trap        3368 non-null   object
 4   l_ear       3332 non-null   object
 5   r_ear       3211 non-null   object
 6   sex         3028 non-null   object
 7   age         1269 non-null   object
 8   weight      2845 non-null   float64
 9   hindft      1633 non-null   float64
 10  notes       243 non-null    object
 11  b_key       3333 non-null   float64
 12  session_id  3380 non-null   int64
 13  study       3217 non-null   object
dtypes: float64(3), int64(1), object(10)
memory usage: 369.8+ KB

- What are the minimum and maximum values for the weight and hind feet measurements?
    - For weight it is 0 for the min and 2365 for the max. Fot hind feet the min is 60 and the max is 160.

In [ ]:
hares[['weight', 'hindft']].describe

            weight       hindft
count  2845.000000  1633.000000
mean   1346.081547   130.872627
std     345.160112    16.155295
min       0.000000    60.000000
25%    1180.000000   128.000000
50%    1400.000000   135.000000
75%    1580.000000   140.000000
max    2365.000000   160.000000

- What are the unique values for some of the categorical columns?

In [17]:
print(hares['grid'].unique())
hares['sex'].unique()

['bonrip' 'bonbs' 'Bonbs' 'bonmat' 'bonmat ']

array([nan, 'M', 'F', '?', 'F?', 'M?', 'pf', 'm', 'f', 'f?', 'm?', 'f ',
       'm '], dtype=object)

- Did any of the issues you anticipated in 1c show up?

Yes they did, there are a lot of inconsistent inputs for how sex was measured. There also seems to be a lot of uncertainty in this column since observations have ?'s following the sex.